
version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  test-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - test-mongo-data:/data/db
  
  user-service:
    build:
      context: ./user
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  
  test-user-service:
    build:
      context: ./user
    command: npm run test
    environment:
      - NODE_ENV=test
    depends_on:
      - test-mongodb

  order-service:
    build:
      context: ./order
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
  
  test-order-service:
    build:
      context: ./order
    command: npm run test
    environment:
      - NODE_ENV=test
    depends_on:
      - test-mongodb

volumes:
  mongo-data:
  test-mongo-data: